routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PostController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('posts', PostController::class);

app/Models/Post.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $fillable = [
        'title', 'description','image'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php
  
namespace App\Http\Controllers;
   
use App\Models\Post;
use Illuminate\Http\Request;
  
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['posts'] = Post::orderBy('id','asc')->paginate(3);
    
        return view('posts.index', $data);
    }
     
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            // benjamin
            $campos=[
            'title' => 'required|max:60',
            'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:4048',
            'description' => 'required|max:600',
            ];
    
            $mensaje=[
                'title.required'=>'El título es requerido',
                'title.max'=>'El título no puede pasar de 60 caracteres',
                'description.required'=>'La descripción es requerido',
                'description.max'=>'La descripción no puede pasar de 600 caracteres',
                'image.required'=>'La foto es requerida',
                'image.image'=>'Elija una imagen',
                'image.mimes'=>'Solo aceptamos formatos: jpg, png, jpeg, gif y svg',
                'image.max'=>'La imagen no debe superar los 4048 kilobytes.'
            ];
            $this->validate($request, $campos, $mensaje);

            // benjamin fin
        $path = $request->file('image')->store('public/images');
        $post = new Post;
        $post->title = $request->title;
        $post->description = $request->description;
        $post->image = $path;
        $post->save();
     
        return redirect()->route('posts.index')
                        ->with('crear','La publicación se ha creado correctamente');
    }
     
    /**
     * Display the specified resource.
     *
     * @param  \App\post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show',compact('post'));
    } 
     
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.edit',compact('post'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id){
            // benjamin
            $campos=[
                'title' => 'required|max:60',
                'description' => 'required|max:600',
                ];
        
                $mensaje=[
                    'title.required'=>'El título es requerido',
                    'title.max'=>'El título no puede pasar de 60 caracteres',
                    'description.required'=>'La descripción es requerido',
                    'description.max'=>'La descripción no puede pasar de 600 caracteres',
                ];
                $this->validate($request, $campos, $mensaje);
    
                // benjamin fin
        $post = Post::find($id);
        if($request->hasFile('image')){
            // $request->validate([
            //   'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
            // ]);
            // benjamin
            $campos=[
                'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:4048',
                ]; 
                $mensaje=[
                    'image.required'=>'La foto es requerida',
                    'image.image'=>'Elija una imagen',
                    'image.mimes'=>'Solo aceptamos formatos: jpg, png, jpeg, gif y svg',
                    'image.max'=>'La imagen no debe superar los 4048 kilobytes.'
                ];
                $this->validate($request, $campos, $mensaje);
                // benjamin fin
            $path = $request->file('image')->store('public/images');
            $post->image = $path;
        }
        $post->title = $request->title;
        $post->description = $request->description;
        $post->save();
    
        return redirect()->route('posts.index')
                        ->with('editar','Publicación actualizada correctamente');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
    
        return redirect()->route('posts.index')
                        ->with('eliminar','La publicación se ha eliminado correctamente');
    }
}

resources/views/posts/create.blade.php
@extends('menu')
@section('contenido')
    <div class="container mt-2">
    
    <div class="row">
        <div class="col-lg-12 mt-2">
            <div class="text-center mb-2">
                <h2 style="font-weight: 900">Añadir Nueva Publicación</h2>
            </div>
            <div class="" style="margin-bottom: 1rem">
                <a class="btn btn-warning" href="{{ route('posts.index') }}"> Atrás</a>
            </div>
        </div>

    </div>
                {{-- benjamin alert --}}
                @if (count($errors)>0)
                <div class="alert alert-danger" role="alert">
                    <ul>
                        @foreach($errors->all() as $error)
                           <li> {{$error}}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                {{-- fin alerta benjamin --}}
    <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data" >
        @csrf

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <input type="text" name="title" class="form-control" placeholder="titulo de la publicación">
                </div>
            </div>
            <div class="mt-3  col-md-12">
                <div class="form-group">
                    <textarea class="form-control" style="height:150px" name="description" placeholder="Descripción De Publicación"></textarea>
                </div>
            </div>        
            <div class="mt-3 col-md-12">
                <div class="form-group">
                    <strong>Imagen De Publicación:</strong>
                    <input type="file" name="image" class="form-control" placeholder="Imagen">
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Guardar</button>
        </div>
    </form>
@endsection

resources/views/posts/edit.blade.php
@extends('menu')
@section('contenido')
        <div class="container mt-2">

                <div class="row">
                    <div class="col-lg-12 mt-2">
                        <div class="text-center mb-2">
                            <h2 style="font-weight: 900">Editar Publicación</h2>
                        </div>
                        <div class="" style="margin-bottom: 1rem">
                            <a class="btn btn-warning" href="{{ route('posts.index') }}"> Atrás</a>
                        </div>
                    </div>
                </div>
            
                {{-- benjamin alert --}}
                @if (count($errors)>0)
                <div class="alert alert-danger" role="alert">
                    <ul>
                        @foreach($errors->all() as $error)
                           <li> {{$error}}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                {{-- fin alerta benjamin --}}
                <form action="{{ route('posts.update',$post->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
            
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Titulo de publicación:</strong>
                                <input type="text" name="title" value="{{ $post->title }}" class="form-control" placeholder="titulo de la publicación">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Descripción de publicación:</strong>
                                <textarea class="form-control" style="height:75px" name="description" placeholder="Descripción de publicación">{{ $post->description }}</textarea>
                            </div>
                        </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Imagen de publicación:</strong>
                            <input type="file" name="image" class="form-control" placeholder="Post Title">
                        </div>
                        <div class="form-group">

                        <img src="{{ Storage::url($post->image) }}" height="200" width="200" alt="" />


                        </div>
                    </div>
                        
                        <button type="submit" class="btn btn-primary ml-3">Guardar</button>
                    
                    </div>
            
                </form>
        </div>
@endsection

resources/views/posts/index.blade.php
@extends('menu')
@section('contenido')
        <div class="container">
            <div class="container mt-3">
                <div class="row">
                        <div class="col-lg-12 margin-tb">
                            <div class="text-center">
                                <h2 style="font-weight: 900">Laravel proyecto listar e insertar</h2>
                            </div>
                            <div class=" mb-3 mt-3" style="margin-bottom: 3rem">
                                <a class="btn btn-success" href="{{ route('posts.create') }}"> Crear nuevo Publicación</a>
                            </div>
                        </div>
                    </div>
                    {{-- benjamin condicional si eliminamos desde controlador  --}}
                    @if ($message = Session::get('eliminar'))
                        <script>
                        Swal.fire(
                            'Eliminado!',
                            'Tu publicación ha sido eliminada.',
                            'Correctamente'
                            )
                        </script>
                    @endif
                    {{--benjamin condicional si editar desde controlador  --}}
                    @if ($message = Session::get('editar'))
                    <script>
                    Swal.fire(
                        'Editado!',
                        'Tu publicación ha sido editada.',
                        'Correctamente'
                        )
                    </script>
                @endif
                    {{--benjamin condicional si crear desde controlador  --}}
                    @if ($message = Session::get('crear'))
                    <script>
                    Swal.fire(
                        'Creado!',
                        'Tu publicación ha sido creada.',
                        'Correctamente'
                        )
                    </script>
                @endif
                    <table class="table table-light">
                        <thead class="thead-light">
                        <tr>
                            <th>Código</th>
                            <th>Imagen</th>
                            <th>Título</th>
                            <th>Descripción</th>
                            <th width="280px">Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($posts as $post)
                        <tr>
                            <td>{{ $post->id }}</td>
                            <td><img src="{{ Storage::url($post->image) }}" height="130" width="250" alt="" /></td>
                            <td>{{ $post->title }}</td>
                            <td>{{ $post->description }}</td>
                            <td>
                                <form action="{{ route('posts.destroy',$post->id) }}" method="POST" class="formulario-eliminar">
                    
                                    <a class="btn btn-primary" href="{{ route('posts.edit',$post->id) }}">Editar</a>
                
                                   
                                    {{-- método de formulario laravel eliminar --}}
                                    @method('DELETE')
                                     @csrf
                                    <button type="submit" class="btn btn-danger">Eliminar</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                
                    {!! $posts->links() !!}
        </div>

@endsection